AWSTemplateFormatVersion: "2010-09-09"
Resources:
  schoolAdmission:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: school-admission
      AttributeDefinitions:
        - AttributeName: "email"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "email"
          KeyType: "HASH"

      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
  MySecretB:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: StudentAdmission
      Description: API Keys of the application
      SecretString: '{"publickey":"oIiOPtIlH0VTdIDK","privatekey":"y474MjaOZXWCuYVRrO9rAVglKqpSnjqStoEMH4EO","workflowid":"etBovddH7BbztJrC","hellosignapikey":"f8956e832d54ca112042bb5f7f6db039b439258c3ffdd5324886379f8673c88a","templateid":"98ca1996af7f995af5d09a7c15b6e4c1101946ac"}'
Outputs:
  TableName:
    Value: !Ref "schoolAdmission"
    Description: Name of the newly created DynamoDB table